{% set name = "matplotlib" %}
{% set version = "3.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b1b60c6476c4cfe9e5cf8ab0d3127476fd3d5f05de0f343a452badaad0e4bdec

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - cycler >=0.10
    - kiwisolver >=1.0.1
    - numpy >=1.15
    - pillow >=6.2.0
    - pip
    - pyparsing >=2.0.3,!=2.0.4,!=2.1.2,!=2.1.6
    - python
    - python-dateutil >=2.1
  run:
    - cycler >=0.10
    - kiwisolver >=1.0.1
    - numpy >=1.15
    - pillow >=6.2.0
    - pyparsing >=2.0.3,!=2.0.4,!=2.1.2,!=2.1.6
    - python
    - python-dateutil >=2.1

test:
  imports:
    - matplotlib
    - matplotlib.axes
    - matplotlib.backends
    - matplotlib.backends.qt_editor
    - matplotlib.cbook
    - matplotlib.compat
    - matplotlib.projections
    - matplotlib.sphinxext
    - matplotlib.style
    - matplotlib.testing
    - matplotlib.testing.jpl_units
    - matplotlib.tests
    - matplotlib.tri
    - mpl_toolkits
    - mpl_toolkits.axes_grid
    - mpl_toolkits.axes_grid1
    - mpl_toolkits.axisartist
    - mpl_toolkits.mplot3d
    - mpl_toolkits.tests

about:
  home: "https://matplotlib.org"
  license: Python Software Foundation
  license_family: OTHER
  license_file: 
  summary: "Python plotting package"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
