{% set name = "sas7bdat" %}
{% set version = "2.2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 484c609d962442203c15bc719a638de992a23cd13bc1971a5af6dfb0daf9f797

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
  host:
    - pip
    - python
    - six >=1.8.0
  run:
    - python
    - six >=1.8.0

test:
  imports:
    - sas7bdat

about:
  home: "https://bitbucket.org/jaredhobbs/sas7bdat"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "A sas7bdat file reader for Python"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - 35838738
